[package]
name = "ifba-saj-tcc"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["IFBA SAJ - ADS"]
description = "Modelo ABNT para TCC do IFBA, campus Santo Antônio de Jesus (ADS), unindo as melhores práticas de diversos projetos Typst acadêmicos."
license = "MIT"
compiler = "0.15.1"
